rollout_type: ofa

## ---- Component search_space ----
# ---- Type ofa ----
search_space_type: ofa
search_space_cfg:
  num_cell_groups: [1, 4, 4, 4, 4, 4]
  expansions: [1, 6, 6, 6, 6, 6]
  kernel_choice: [7, 5, 3]
  width_choice: [6, 4, 3]
  depth_choice: [4, 3, 2]
  # schedule_cfg:
  #   kernel_choice:
  #       type: value
  #       boundary: [1, 51, 120]
  #       value: [[7], [7, 5], [7, 5, 3]]
  #   width_choice:
  #     type: value
  #     boundary: [1, 180, 240]
  #     value: [[6], [6,5,4], [6,5,4,3,2]]
  #   depth_choice:
  #     type: value
  #     boundary: [1, 300, 360]
  #     value: [[4], [4, 3], [4,3,2]]
# ---- End Type mnsanet_ofa ----
## ---- End Component search_space ----

## ---- Component dataset ----
# ---- Type cifar10 ----
dataset_type: imagenet
dataset_cfg:
  # Schedulable attributes: 
  load_train_only: false
  class_name_file: null
  random_choose: false
  random_seed: 123
# ---- End Type cifar10 ----
## ---- End Component dataset ----

## ---- Component controller ----
# ---- Type rl ----
controller_type: ofa
controller_cfg:
  # Schedulable attributes:
  rollout_type: ofa
# ---- End Type rl ----
## ---- End Component controller ----

## ---- Component evaluator ----
# ---- Type mepa ----
evaluator_type: mepa
evaluator_cfg:
  # Schedulable attributes: controller_surrogate_steps, mepa_surrogate_steps, mepa_samples
  load_optimizer: false
  load_scheduler: false
  rollout_type: ofa
  batch_size: 96
  controller_surrogate_steps: 0
  # derive_surrogate_steps: 0
  mepa_surrogate_steps: 0
  mepa_optimizer:
    lr: 0.005
    momentum: 0.9
    type: SGD
    weight_decay: 0.0001
  mepa_scheduler:
    eta_min: 0.0
    T_max: 10
    type: CosineAnnealingLR
  surrogate_optimizer: null
  surrogate_scheduler: null
  mepa_samples: 1
  data_portion:
  - 0.0
  - [train, 1.0] # train evaluator weights
  - [test, 0.1] # for train controller
  mepa_as_surrogate: false
  bptt_steps: 35
  schedule_cfg: null
# ---- End Type mepa ----
## ---- End Component evaluator ----

## ---- Component weights_manager ----
# ---- Type supernet ----gal
weights_manager_type: ofa_supernet
weights_manager_cfg:
  # Schedulable attributes: 
  rollout_type: ofa
  backbone_type: mbv3_backbone
  backbone_cfg:
    blocks: [1, 4, 4, 4, 4, 4]
    strides: [1, 2, 2, 2, 1, 2]
    expansions: [1, 6, 6, 6, 6, 6]
    layer_channels: [16, 16, 24, 40, 80, 112, 160, 960, 1280]
    mult_ratio: 1.
    kernel_sizes: [3, 5, 7]
    num_classes: 1000
    block_type: mbv3_block
    pretrained_path: /home/tangchangcheng/scripts/ofa_supernet_flex.pt
# ---- End Type supernet ----
## ---- End Component weights_manager ----

objective_type: ofa_classification
objective_cfg:
  # Schedulable attributes:
  schedule_cfg:
    soft_loss_coeff:
      type: value
      boundary: [1, 60]
      value: [0.0, 1.0]
  soft_loss_coeff: 0.0
  latency_coeff: 1.0
  expect_latency: 20
  reward: mult
  punishment: hard
#   latency_file: latency_block.txt

## ---- Component trainer ----
# ---- Type simple ----
trainer_type: simple
trainer_cfg:
  # Schedulable attributes: controller_samples, derive_samples
  rollout_type: ofa
  epochs: 500
  test_every: 10
  controller_scheduler: null
  controller_samples: 1
  derive_samples: 8
  evaluator_steps: null
  controller_steps: 0
  controller_train_every: 1
  controller_train_begin: 1001
  interleave_controller_every: null
  schedule_cfg: null
# ---- End Type simple ----
## ---- End Component trainer ----
